### ISSUE TITLE
jacks-context.py throws exception when no passphrase present 

### ISSUE THREAD

**Issue by hussamnasir** [Jacks-GENI/jacks-context#19]
Changing Line 45  to key_passphrase=False resolves the issue.

nasir@thirdday:~/jacks-context$ ./portal.sh 
Private key passphrase: Traceback (most recent call last):
  File "jacks-context.py", line 45, in <module>
    context = geni.util.loadContext(key_passphrase=True)
  File "/usr/local/lib/python2.7/dist-packages/geni/util.py", line 266, in loadContext
    key_passphrase = getpass.getpass("Private key passphrase: ")
  File "/usr/lib/python2.7/getpass.py", line 71, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
  File "/usr/lib/python2.7/getpass.py", line 133, in _raw_input
    line = input.readline()
KeyboardInterrupt

**Comment by tcmitchell** [comment]
With `key_passphrase=True`, will it work if you hit return when prompted for your private key passphrase? This should enter an empty passphrase, which should work with private keys that have no passphrase.

**Comment by hussamnasir** [comment]
Yes it does . Sorry did not try that.

**Comment by tcmitchell** [comment]
Nick pointed me at a better way to handle this, patch forthcoming.
